"""add source_breakdown and pallet_licence_ids to inter_warehouse_transfers

Revision ID: 33f4ab41ca55
Revises: 480bab1558bf
Create Date: 2026-03-12 15:23:54.011793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f4ab41ca55'
down_revision: Union[str, Sequence[str], None] = '480bab1558bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inter_warehouse_transfers', sa.Column('source_breakdown', sa.JSON(), nullable=True))
    op.add_column('inter_warehouse_transfers', sa.Column('pallet_licence_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inter_warehouse_transfers', 'pallet_licence_ids')
    op.drop_column('inter_warehouse_transfers', 'source_breakdown')
    # ### end Alembic commands ###
