"""add_inventory_deducted_to_inter_warehouse_transfers

Revision ID: 480bab1558bf
Revises: g2b3c4d5e6f7
Create Date: 2026-03-12 11:50:30.077617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480bab1558bf'
down_revision: Union[str, Sequence[str], None] = 'g2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inter_warehouse_transfers', sa.Column('inventory_deducted', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inter_warehouse_transfers', 'inventory_deducted')
    # ### end Alembic commands ###
