"""initial schema

Revision ID: 6178999f0cff
Revises: 
Create Date: 2026-02-26 08:42:28.283672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6178999f0cff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_badge_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_badge_id'), table_name='users')
    op.create_index(op.f('ix_users_badge_id'), 'users', ['badge_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_badge_id'), table_name='users')
    op.create_index(op.f('ix_users_badge_id'), 'users', ['badge_id'], unique=False)
    op.create_unique_constraint(op.f('users_badge_id_key'), 'users', ['badge_id'])
    # ### end Alembic commands ###
