"""warehouse_category_access

Revision ID: b5e4cbc753b3
Revises: a3f8c2d1e9b4
Create Date: 2026-02-26 16:07:29.516016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e4cbc753b3'
down_revision: Union[str, Sequence[str], None] = 'a3f8c2d1e9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_badge_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_badge_id'), table_name='users')
    op.create_index(op.f('ix_users_badge_id'), 'users', ['badge_id'], unique=True)
    op.add_column('warehouses', sa.Column('allow_product_creation', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'allow_product_creation')
    op.drop_index(op.f('ix_users_badge_id'), table_name='users')
    op.create_index(op.f('ix_users_badge_id'), 'users', ['badge_id'], unique=False)
    op.create_unique_constraint(op.f('users_badge_id_key'), 'users', ['badge_id'])
    # ### end Alembic commands ###
