"""ingredient container serialization: intakes, lots, containers, event ledger

Revision ID: v7w8x9y0z1a2
Revises: u6v7w8x9y0z1
Create Date: 2026-08-03

Creates the four tables behind INGREDIENT-SERIALIZATION-SPEC.md Phase 1. Purely
additive — no existing table is touched, so there is no data migration and
nothing to roll back beyond dropping the new tables.

Every CREATE is guarded. Alembic does not own this schema: Base.metadata.create_all
runs at app import (backend/main.py:29), so on any box where the app has started
since these models landed, the tables already exist. entrypoint.sh runs
`alembic upgrade head` under `set -e` before the app starts, so an unguarded
CREATE TABLE against an existing table raises DuplicateTable, fails the
entrypoint, and crash-loops the container — i.e. the warehouse goes down mid-shift.
The guards make this migration safe to apply to a database in either state.

Hand-written rather than autogenerated for the same reason: autogenerate diffs
the models against a dev database where create_all has already created these
tables, and would have produced an empty upgrade().
"""
from alembic import op
import sqlalchemy as sa


revision = "v7w8x9y0z1a2"
down_revision = "u6v7w8x9y0z1"
branch_labels = None
depends_on = None


NEW_TABLES = ("ingredient_intakes", "intake_lots", "containers", "container_events")


def _existing_tables(bind):
    return set(sa.inspect(bind).get_table_names())


def upgrade():
    bind = op.get_bind()
    existing = _existing_tables(bind)

    if "ingredient_intakes" not in existing:
        op.create_table(
            "ingredient_intakes",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column("intake_number", sa.String(length=30), nullable=True),
            sa.Column("vendor_id", sa.String(length=50), nullable=True),
            sa.Column("bol", sa.String(length=100), nullable=True),
            sa.Column("purchase_order", sa.String(length=100), nullable=True),
            sa.Column("receipt_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("warehouse_id", sa.String(length=50), nullable=True),
            sa.Column("status", sa.String(length=24), nullable=True),
            sa.Column("source", sa.String(length=20), server_default="truck", nullable=False),
            sa.Column("expected_count", sa.Integer(), nullable=True),
            sa.Column("received_count", sa.Integer(), nullable=True),
            sa.Column("short_count", sa.Integer(), nullable=True),
            sa.Column("short_reason", sa.Text(), nullable=True),
            sa.Column("over_received", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("over_reason", sa.Text(), nullable=True),
            sa.Column("damaged_count", sa.Integer(), nullable=True),
            sa.Column("last_serial_seq", sa.Integer(), server_default="0", nullable=False),
            sa.Column("submitted_by", sa.String(length=50), nullable=True),
            sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("approved_by", sa.String(length=50), nullable=True),
            sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("rejected_by_id", sa.String(length=50), nullable=True),
            sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("rejection_reason", sa.Text(), nullable=True),
            sa.Column("rejection_disposition", sa.String(length=24), nullable=True),
            sa.Column("voided_by_id", sa.String(length=50), nullable=True),
            sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("void_reason", sa.Text(), nullable=True),
            sa.Column("notes", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("deleted_by_id", sa.String(length=50), nullable=True),
            sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"]),
            sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"]),
            sa.ForeignKeyConstraint(["submitted_by"], ["users.id"]),
            sa.ForeignKeyConstraint(["approved_by"], ["users.id"]),
            sa.ForeignKeyConstraint(["rejected_by_id"], ["users.id"]),
            sa.ForeignKeyConstraint(["voided_by_id"], ["users.id"]),
            sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_ingredient_intakes_intake_number", "ingredient_intakes", ["intake_number"], unique=True)
        op.create_index("ix_ingredient_intakes_warehouse_id", "ingredient_intakes", ["warehouse_id"])
        op.create_index("ix_ingredient_intakes_status", "ingredient_intakes", ["status"])

    if "intake_lots" not in existing:
        op.create_table(
            "intake_lots",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column("intake_id", sa.String(length=50), nullable=False),
            sa.Column("product_id", sa.String(length=50), nullable=False),
            sa.Column("category_id", sa.String(length=50), nullable=True),
            sa.Column("container_type", sa.String(length=10), nullable=False),
            sa.Column("vendor_lot", sa.String(length=100), nullable=True),
            sa.Column("lot_unknown", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("bbd", sa.DateTime(timezone=True), nullable=True),
            sa.Column("expected_count", sa.Integer(), nullable=True),
            sa.Column("brix", sa.Float(), nullable=True),
            sa.Column("net_weight_per_container", sa.Float(), nullable=True),
            sa.Column("weight_unit", sa.String(length=20), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["intake_id"], ["ingredient_intakes.id"]),
            sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
            sa.ForeignKeyConstraint(["category_id"], ["categories.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_intake_lots_intake_id", "intake_lots", ["intake_id"])
        op.create_index("ix_intake_lots_product_id", "intake_lots", ["product_id"])
        op.create_index("ix_intake_lots_vendor_lot", "intake_lots", ["vendor_lot"])
        op.create_index("ix_intake_lots_bbd", "intake_lots", ["bbd"])

    if "containers" not in existing:
        op.create_table(
            "containers",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column("serial", sa.String(length=100), nullable=False),
            sa.Column("sequence", sa.Integer(), nullable=False),
            sa.Column("intake_id", sa.String(length=50), nullable=False),
            sa.Column("intake_lot_id", sa.String(length=50), nullable=False),
            sa.Column("product_id", sa.String(length=50), nullable=False),
            sa.Column("warehouse_id", sa.String(length=50), nullable=True),
            sa.Column("container_type", sa.String(length=10), nullable=False),
            sa.Column("status", sa.String(length=24), nullable=True),
            sa.Column("remaining_qty", sa.Float(), nullable=True),
            sa.Column("net_weight", sa.Float(), nullable=True),
            sa.Column("qty_unit", sa.String(length=20), nullable=True),
            sa.Column("vendor_lot", sa.String(length=100), nullable=True),
            sa.Column("bbd", sa.DateTime(timezone=True), nullable=True),
            sa.Column("storage_row_id", sa.String(length=50), nullable=True),
            sa.Column("pallet_group_id", sa.String(length=50), nullable=True),
            sa.Column("is_held", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("hold_reason", sa.Text(), nullable=True),
            sa.Column("held_by", sa.String(length=50), nullable=True),
            sa.Column("held_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("staged_for_request_id", sa.String(length=50), nullable=True),
            sa.Column("consumed_by_batch_uid", sa.String(length=100), nullable=True),
            sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("scanned_by", sa.String(length=50), nullable=True),
            sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("deleted_by_id", sa.String(length=50), nullable=True),
            sa.ForeignKeyConstraint(["intake_id"], ["ingredient_intakes.id"]),
            sa.ForeignKeyConstraint(["intake_lot_id"], ["intake_lots.id"]),
            sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
            sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"]),
            sa.ForeignKeyConstraint(["storage_row_id"], ["storage_rows.id"]),
            sa.ForeignKeyConstraint(["held_by"], ["users.id"]),
            sa.ForeignKeyConstraint(["scanned_by"], ["users.id"]),
            sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("intake_id", "sequence", name="uq_container_intake_sequence"),
        )
        op.create_index("ix_containers_serial", "containers", ["serial"], unique=True)
        op.create_index("ix_containers_intake_id", "containers", ["intake_id"])
        op.create_index("ix_containers_intake_lot_id", "containers", ["intake_lot_id"])
        op.create_index("ix_containers_product_id", "containers", ["product_id"])
        op.create_index("ix_containers_warehouse_id", "containers", ["warehouse_id"])
        op.create_index("ix_containers_status", "containers", ["status"])
        op.create_index("ix_containers_vendor_lot", "containers", ["vendor_lot"])
        op.create_index("ix_containers_bbd", "containers", ["bbd"])
        op.create_index("ix_containers_storage_row_id", "containers", ["storage_row_id"])
        op.create_index("ix_containers_pallet_group_id", "containers", ["pallet_group_id"])
        op.create_index("ix_containers_staged_for_request_id", "containers", ["staged_for_request_id"])
        op.create_index("ix_containers_consumed_by_batch_uid", "containers", ["consumed_by_batch_uid"])

    if "container_events" not in existing:
        # Explicit sequence: SQLAlchemy's Sequence() on the model emits the same
        # object under create_all, so both schema paths converge.
        op.execute("CREATE SEQUENCE IF NOT EXISTS container_events_seq_seq")
        op.create_table(
            "container_events",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column(
                "seq", sa.BigInteger(),
                server_default=sa.text("nextval('container_events_seq_seq')"),
                nullable=False,
            ),
            sa.Column("container_id", sa.String(length=50), nullable=False),
            sa.Column("event_type", sa.String(length=30), nullable=False),
            sa.Column("from_status", sa.String(length=24), nullable=True),
            sa.Column("to_status", sa.String(length=24), nullable=False),
            sa.Column("from_row_id", sa.String(length=50), nullable=True),
            sa.Column("to_row_id", sa.String(length=50), nullable=True),
            sa.Column("qty_delta", sa.Float(), nullable=True),
            sa.Column("actor_id", sa.String(length=50), nullable=True),
            sa.Column("ref_type", sa.String(length=30), nullable=True),
            sa.Column("ref_id", sa.String(length=50), nullable=True),
            sa.Column("reason", sa.Text(), nullable=True),
            sa.Column("reason_code", sa.String(length=30), nullable=True),
            sa.Column("verified", sa.Boolean(), server_default="true", nullable=False),
            sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.Column("idempotency_key", sa.String(length=64), nullable=True),
            sa.ForeignKeyConstraint(["container_id"], ["containers.id"]),
            sa.ForeignKeyConstraint(["from_row_id"], ["storage_rows.id"]),
            sa.ForeignKeyConstraint(["to_row_id"], ["storage_rows.id"]),
            sa.ForeignKeyConstraint(["actor_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_container_events_seq", "container_events", ["seq"], unique=True)
        op.create_index("ix_container_events_container_id", "container_events", ["container_id"])
        op.create_index("ix_container_events_event_type", "container_events", ["event_type"])
        op.create_index("ix_container_events_occurred_at", "container_events", ["occurred_at"])
        op.create_index("ix_container_events_idempotency_key", "container_events", ["idempotency_key"], unique=True)


def downgrade():
    bind = op.get_bind()
    existing = _existing_tables(bind)

    # Reverse dependency order.
    for table in ("container_events", "containers", "intake_lots", "ingredient_intakes"):
        if table in existing:
            op.drop_table(table)
    op.execute("DROP SEQUENCE IF EXISTS container_events_seq_seq")
