"""lot-level material identity + unit-count placements

Revision ID: z1a2b3c4d5e6
Revises: y0z1a2b3c4d5
Create Date: 2026-08-13

Phase 1 of the lot-level ingredient model. Purely additive — no existing table's
data is touched, only two nullable columns are added to sub_locations and one
nullable FK to receipts.

WHY THE GUARDS. Alembic does not own this schema: `Base.metadata.create_all`
runs at app import (backend/main.py:33), so on any box where the app has started
since these models landed, the tables already exist. `entrypoint.sh` then runs
`alembic upgrade head` under `set -e` BEFORE the app starts, so an unguarded
CREATE against an existing object raises DuplicateTable, fails the entrypoint,
and crash-loops the container — i.e. the warehouse goes down mid-shift. Every
CREATE and ALTER below is therefore inspector-guarded, and the migration is safe
to apply to a database in either state.

Hand-written rather than autogenerated for the same reason: autogenerate diffs
the models against a dev database where create_all has already made these
tables, and would emit an empty upgrade().
"""
from alembic import op
import sqlalchemy as sa


revision = "z1a2b3c4d5e6"
down_revision = "y0z1a2b3c4d5"
branch_labels = None
depends_on = None


NEW_TABLES = (
    "material_lots",
    "material_lot_bbd_extensions",
    "lot_placements",
    "lot_placement_events",
)


def _tables(bind):
    return set(sa.inspect(bind).get_table_names())


def _columns(bind, table):
    return {c["name"] for c in sa.inspect(bind).get_columns(table)}


def _index_names(bind, table):
    return {i["name"] for i in sa.inspect(bind).get_indexes(table)}


def _fk_names_on(bind, table, column):
    """Actual FK constraint names touching `column`, whatever they are called.

    The name is NOT knowable in advance. Applying this migration names the
    constraint `fk_receipts_material_lot_id`; letting create_all build the schema
    instead has SQLAlchemy name it `receipts_material_lot_id_fkey`. Both states
    exist in the wild for exactly the reason the module docstring gives, so
    downgrade looks the name up rather than assuming one.
    """
    return {
        fk["name"]
        for fk in sa.inspect(bind).get_foreign_keys(table)
        if fk.get("name") and column in (fk.get("constrained_columns") or [])
    }


def upgrade():
    bind = op.get_bind()
    existing = _tables(bind)

    # ── material_lots ────────────────────────────────────────────────────────
    if "material_lots" not in existing:
        op.create_table(
            "material_lots",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column("lot_code", sa.String(length=30), nullable=False),
            sa.Column("lot_key", sa.String(length=255), nullable=False),
            sa.Column("product_id", sa.String(length=50), nullable=False),
            sa.Column("vendor_id", sa.String(length=50), nullable=True),
            sa.Column("vendor_lot_number", sa.String(length=100), nullable=True),
            sa.Column("lot_unknown", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("bbd_original", sa.DateTime(timezone=True), nullable=True),
            sa.Column("bbd_current", sa.DateTime(timezone=True), nullable=True),
            sa.Column("unit_label", sa.String(length=20), server_default="unit", nullable=False),
            sa.Column("weight_per_unit", sa.Float(), nullable=True),
            sa.Column("weight_unit", sa.String(length=10), nullable=True),
            sa.Column("brix", sa.Float(), nullable=True),
            sa.Column("warehouse_id", sa.String(length=50), nullable=True),
            sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
            sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("review_reason", sa.Text(), nullable=True),
            sa.Column("first_received_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("last_received_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("label_printed_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("is_held", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("hold_reason", sa.Text(), nullable=True),
            sa.Column("held_by", sa.String(length=50), nullable=True),
            sa.Column("held_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("deleted_by_id", sa.String(length=50), nullable=True),
            sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
            sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"]),
            sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"]),
            sa.ForeignKeyConstraint(["held_by"], ["users.id"]),
            sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_material_lots_lot_code", "material_lots", ["lot_code"], unique=True)
        op.create_index("ix_material_lots_lot_key", "material_lots", ["lot_key"], unique=True)
        op.create_index("ix_material_lots_product_id", "material_lots", ["product_id"])
        op.create_index("ix_material_lots_vendor_id", "material_lots", ["vendor_id"])
        op.create_index("ix_material_lots_warehouse_id", "material_lots", ["warehouse_id"])
        op.create_index("ix_material_lots_bbd_original", "material_lots", ["bbd_original"])
        op.create_index("ix_material_lots_bbd_current", "material_lots", ["bbd_current"])

    # ── material_lot_bbd_extensions ──────────────────────────────────────────
    if "material_lot_bbd_extensions" not in existing:
        op.create_table(
            "material_lot_bbd_extensions",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column("material_lot_id", sa.String(length=50), nullable=False),
            sa.Column("previous_bbd", sa.DateTime(timezone=True), nullable=True),
            sa.Column("new_bbd", sa.DateTime(timezone=True), nullable=False),
            sa.Column("reason", sa.Text(), nullable=False),
            sa.Column("supporting_doc_ref", sa.String(length=200), nullable=True),
            sa.Column("requested_by", sa.String(length=50), nullable=True),
            sa.Column("requested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("approved_by", sa.String(length=50), nullable=True),
            sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.ForeignKeyConstraint(["material_lot_id"], ["material_lots.id"]),
            sa.ForeignKeyConstraint(["requested_by"], ["users.id"]),
            sa.ForeignKeyConstraint(["approved_by"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            "ix_material_lot_bbd_extensions_material_lot_id",
            "material_lot_bbd_extensions", ["material_lot_id"],
        )

    # ── lot_placements ───────────────────────────────────────────────────────
    if "lot_placements" not in existing:
        op.create_table(
            "lot_placements",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column("material_lot_id", sa.String(length=50), nullable=False),
            sa.Column("storage_row_id", sa.String(length=50), nullable=False),
            sa.Column("product_id", sa.String(length=50), nullable=False),
            sa.Column("warehouse_id", sa.String(length=50), nullable=True),
            sa.Column("full_units", sa.Integer(), server_default="0", nullable=False),
            sa.Column("open_units", sa.Integer(), server_default="0", nullable=False),
            sa.Column("open_remaining_qty", sa.Float(), server_default="0", nullable=False),
            sa.Column("last_counted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("last_counted_by", sa.String(length=50), nullable=True),
            sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["material_lot_id"], ["material_lots.id"]),
            sa.ForeignKeyConstraint(["storage_row_id"], ["storage_rows.id"]),
            sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
            sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"]),
            sa.ForeignKeyConstraint(["last_counted_by"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
            # One (lot, row) = one answer. Without this two concurrent put-aways
            # create two rows and the count silently answers twice.
            sa.UniqueConstraint("material_lot_id", "storage_row_id", name="uq_lot_placement_lot_row"),
            sa.CheckConstraint("full_units >= 0", name="ck_lot_placement_full_units_nonneg"),
            sa.CheckConstraint("open_units >= 0", name="ck_lot_placement_open_units_nonneg"),
            sa.CheckConstraint("open_remaining_qty >= 0", name="ck_lot_placement_open_qty_nonneg"),
            sa.CheckConstraint(
                "open_units > 0 OR open_remaining_qty = 0",
                name="ck_lot_placement_open_qty_requires_unit",
            ),
        )
        op.create_index("ix_lot_placements_material_lot_id", "lot_placements", ["material_lot_id"])
        op.create_index("ix_lot_placements_storage_row_id", "lot_placements", ["storage_row_id"])
        op.create_index("ix_lot_placements_product_id", "lot_placements", ["product_id"])
        op.create_index("ix_lot_placements_warehouse_id", "lot_placements", ["warehouse_id"])

    # ── lot_placement_events ─────────────────────────────────────────────────
    if "lot_placement_events" not in existing:
        # Explicit sequence: SQLAlchemy's Sequence() on the model emits the same
        # object under create_all, so both schema paths converge.
        op.execute("CREATE SEQUENCE IF NOT EXISTS lot_placement_events_seq_seq")
        op.create_table(
            "lot_placement_events",
            sa.Column("id", sa.String(length=50), nullable=False),
            sa.Column(
                "seq", sa.BigInteger(),
                server_default=sa.text("nextval('lot_placement_events_seq_seq')"),
                nullable=False,
            ),
            sa.Column("material_lot_id", sa.String(length=50), nullable=False),
            sa.Column("storage_row_id", sa.String(length=50), nullable=False),
            sa.Column("counterpart_row_id", sa.String(length=50), nullable=True),
            sa.Column("event_type", sa.String(length=30), nullable=False),
            sa.Column("full_units_delta", sa.Integer(), server_default="0", nullable=False),
            sa.Column("open_units_delta", sa.Integer(), server_default="0", nullable=False),
            sa.Column("qty_delta", sa.Float(), server_default="0", nullable=False),
            sa.Column("actor_id", sa.String(length=50), nullable=True),
            sa.Column("ref_type", sa.String(length=30), nullable=True),
            sa.Column("ref_id", sa.String(length=50), nullable=True),
            sa.Column("reason", sa.Text(), nullable=True),
            sa.Column("reason_code", sa.String(length=30), nullable=True),
            sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.Column("idempotency_key", sa.String(length=64), nullable=True),
            sa.ForeignKeyConstraint(["material_lot_id"], ["material_lots.id"]),
            sa.ForeignKeyConstraint(["storage_row_id"], ["storage_rows.id"]),
            sa.ForeignKeyConstraint(["counterpart_row_id"], ["storage_rows.id"]),
            sa.ForeignKeyConstraint(["actor_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_lot_placement_events_seq", "lot_placement_events", ["seq"], unique=True)
        op.create_index("ix_lot_placement_events_material_lot_id", "lot_placement_events", ["material_lot_id"])
        op.create_index("ix_lot_placement_events_storage_row_id", "lot_placement_events", ["storage_row_id"])
        op.create_index("ix_lot_placement_events_event_type", "lot_placement_events", ["event_type"])
        op.create_index("ix_lot_placement_events_occurred_at", "lot_placement_events", ["occurred_at"])
        op.create_index(
            "ix_lot_placement_events_idempotency_key",
            "lot_placement_events", ["idempotency_key"], unique=True,
        )

    # ── additive columns on existing tables ──────────────────────────────────
    if "sub_locations" in existing:
        cols = _columns(bind, "sub_locations")
        if "storage_unit" not in cols:
            op.add_column("sub_locations", sa.Column("storage_unit", sa.String(length=20), nullable=True))
        if "unit_capacity" not in cols:
            op.add_column("sub_locations", sa.Column("unit_capacity", sa.Integer(), nullable=True))

    if "receipts" in existing:
        cols = _columns(bind, "receipts")
        if "material_lot_id" not in cols:
            op.add_column("receipts", sa.Column("material_lot_id", sa.String(length=50), nullable=True))
            op.create_foreign_key(
                "fk_receipts_material_lot_id", "receipts", "material_lots",
                ["material_lot_id"], ["id"],
            )
            op.create_index("ix_receipts_material_lot_id", "receipts", ["material_lot_id"])


def downgrade():
    bind = op.get_bind()
    existing = _tables(bind)

    if "receipts" in existing and "material_lot_id" in _columns(bind, "receipts"):
        if "ix_receipts_material_lot_id" in _index_names(bind, "receipts"):
            op.drop_index("ix_receipts_material_lot_id", table_name="receipts")
        for name in _fk_names_on(bind, "receipts", "material_lot_id"):
            op.drop_constraint(name, "receipts", type_="foreignkey")
        op.drop_column("receipts", "material_lot_id")

    if "sub_locations" in existing:
        cols = _columns(bind, "sub_locations")
        if "unit_capacity" in cols:
            op.drop_column("sub_locations", "unit_capacity")
        if "storage_unit" in cols:
            op.drop_column("sub_locations", "storage_unit")

    # Reverse dependency order.
    for table in ("lot_placement_events", "lot_placements",
                  "material_lot_bbd_extensions", "material_lots"):
        if table in existing:
            op.drop_table(table)
    op.execute("DROP SEQUENCE IF EXISTS lot_placement_events_seq_seq")
